apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: app
  name: app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: app
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.30.0 (9d8dcb518)
      creationTimestamp: null
      labels:
        io.kompose.network/dotnet-food-dev: "true"
        io.kompose.service: app
    spec:
      containers:
        - env:
            - name: ASPNETCORE_URLS
              value: http://+:80
            - name: ConnectionStrings__DefaultConnection
              value: User ID=postgres;Server=db;Port=5432;Database=sample_db;Password=example;
          image: fskickz/food:1.1
          name: app-services
          ports:
            - containerPort: 80
              hostPort: 5001
              protocol: TCP
          resources: {}
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 45
            timeoutSeconds: 2
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30
            timeoutSeconds: 2
      restartPolicy: Always
status: {}
